# docker container run --name stateless-auth-db -p 5432:5432 -e POSTGRES_DB=auth-db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres postgres:latest
# docker container run --name stateful-auth-db -p 5433:5432 -e POSTGRES_DB=auth-db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres postgres:latest
# docker container run --name token-redis -p 6379 redis:latest -d

version: '3'
services:
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db  
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    networks:
      - auth  
    ports:
      - "5432:5432"
  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db  
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    networks:
      - auth    
    ports:
      - "5433:5432"

  token-redis:
    container_name: token-redis
    image: redis:latest
    networks:
      - auth  
    ports:
      - "6379:6379"

networks:
  auth:
    driver: bridge      

